// Generated by CoffeeScript 1.3.3
(function() {
  var getValue;

  module.exports.setupBackboneSync = function(options) {
    var storage;
    if (options == null) {
      options = {};
    }
    if (options instanceof this) {
      storage = options;
    } else {
      storage = new this(options);
    }
    return function(method, object, options) {
      var address, input;
      if (options == null) {
        options = {};
      }
      address = getValue(object, "storageAddress") || getValue(object, "url");
      input = (function() {
        switch (method) {
          case "read":
            return getValue(object, "criteria");
          case "create":
          case "update":
            return object.toJSON();
        }
      })();
      return storage[method](address, input, function(error, output, response, request) {
        var callback;
        callback = error ? "error" : "success";
        return options[callback](object, output, options);
      });
    };
  };

  getValue = function(object, member) {
    var _ref;
    if ((_ref = object[member]) != null ? _ref.call : void 0) {
      return object[member]();
    } else {
      return object[member];
    }
  };

}).call(this);
