// Generated by CoffeeScript 1.10.0
(function() {
  var extend;

  extend = require("underscore").extend;

  module.exports = {
    index: function(address, attributes, callback) {
      if (callback == null) {
        callback = this.defaultCallback;
      }
      return this.request("PUT", {
        path: address,
        body: attributes,
        done: function(error, output, response, request) {
          return callback(error, void 0, response, request);
        }
      });
    },
    search: function(address, criteria, callback) {
      if (callback == null) {
        callback = this.defaultCallback;
      }
      return this.request("POST", {
        path: address + "/_search",
        body: criteria,
        done: function(error, output, response, request) {
          var _id, _score, _source, _type, highlight, hits;
          if (output) {
            hits = (function() {
              var i, len, ref, ref1, results;
              ref = output.hits.hits;
              results = [];
              for (i = 0, len = ref.length; i < len; i++) {
                ref1 = ref[i], _id = ref1._id, _score = ref1._score, _source = ref1._source, _type = ref1._type, highlight = ref1.highlight;
                results.push({
                  score: _score,
                  collection: _type,
                  record: extend(_source, {
                    id: _id
                  }),
                  highlights: highlight
                });
              }
              return results;
            })();
            hits.total = output.hits.total;
            hits.highScore = output.hits.max_score;
          }
          return callback(error, hits, response, request);
        }
      });
    }
  };

}).call(this);
